"""Skill 3 — Code Generation & Execution

Agentic code generation with iterative testing and auto-fixing.
Generates code file by file, runs tests, lints, and fixes errors until tests pass.
"""

import os
import json
import time
import subprocess
import logging
from typing import Any, Dict, Optional, List
from jarvis.skills.base import Skill, SkillResult

logger = logging.getLogger(__name__)


class CodeExecutorSkill(Skill):
    """
    Code generation & execution skill with agentic loops.
    
    Features:
    - Generate code file by file from architecture spec
    - Run tests (Jest/Pytest)
    - Lint code (ESLint/Ruff)
    - Auto-fix errors
    - Iterate until tests pass
    """
    
    def __init__(self):
        super().__init__()
        self._name = "code_executor"
        self._description = (
            "Agentic code generation and execution. "
            "Generates code from spec, runs tests, lints, auto-fixes errors, "
            "and iterates until tests pass."
        )
        self._parameters = {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "description": "Action: 'generate' code, 'test' run tests, 'lint' check code, 'fix' auto-fix, 'iterate' full loop",
                    "enum": ["generate", "test", "lint", "fix", "iterate"]
                },
                "spec_path": {
                    "type": "string",
                    "description": "Path to architecture spec (PLAN.md or JSON)"
                },
                "project_dir": {
                    "type": "string",
                    "description": "Project directory to work in"
                },
                "max_iterations": {
                    "type": "integer",
                    "description": "Maximum iterations for auto-fix loop (default: 5)"
                }
            },
            "required": ["action"]
        }
        
        self._llm_api_key = os.getenv("LLM_API_KEY")
    
    def _run_command(self, cmd: str, cwd: str = None, timeout: int = 60) -> Dict[str, Any]:
        """Run shell command and return result."""
        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True,
                cwd=cwd or os.getcwd(), timeout=timeout
            )
            return {
                "stdout": result.stdout,
                "stderr": result.stderr,
                "returncode": result.returncode,
                "success": result.returncode == 0
            }
        except subprocess.TimeoutExpired:
            return {"stdout": "", "stderr": "Command timed out", "returncode": -1, "success": False}
        except Exception as e:
            return {"stdout": "", "stderr": str(e), "returncode": -1, "success": False}
    
    def _generate_code(self, spec_path: str, project_dir: str) -> tuple[bool, List[str], Optional[str]]:
        """
        Generate code files from architecture spec.
        
        In production, this would use Claude API with agentic tool use
        to generate files one by one.
        """
        if not self._llm_api_key:
            return False, [], "LLM_API_KEY not configured"
        
        # TODO: Implement Claude API integration for code generation
        # For now, create placeholder structure
        
        try:
            os.makedirs(project_dir, exist_ok=True)
            
            # Create basic structure
            files_created = []
            
            # package.json
            package_json = {
                "name": os.path.basename(project_dir),
                "version": "1.0.0",
                "scripts": {
                    "dev": "node server.js",
                    "test": "jest",
                    "lint": "eslint ."
                }
            }
            package_path = os.path.join(project_dir, "package.json")
            with open(package_path, 'w') as f:
                json.dump(package_json, f, indent=2)
            files_created.append(package_path)
            
            # server.js
            server_code = """const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

module.exports = app;
"""
            server_path = os.path.join(project_dir, "server.js")
            with open(server_path, 'w') as f:
                f.write(server_code)
            files_created.append(server_path)
            
            # README.md
            readme = f"""# {os.path.basename(project_dir)}

Generated by JARVIS Code Executor

## Setup
```bash
npm install
npm run dev
```

## Test
```bash
npm test
```
"""
            readme_path = os.path.join(project_dir, "README.md")
            with open(readme_path, 'w') as f:
                f.write(readme)
            files_created.append(readme_path)
            
            return True, files_created, None
            
        except Exception as e:
            logger.error(f"Code generation failed: {e}")
            return False, [], str(e)
    
    def _run_tests(self, project_dir: str) -> tuple[bool, str, Optional[str]]:
        """Run tests in project directory."""
        # Detect test framework
        if os.path.exists(os.path.join(project_dir, "package.json")):
            # Node.js project
            result = self._run_command("npm test -- --watchAll=false", cwd=project_dir, timeout=120)
        elif os.path.exists(os.path.join(project_dir, "pytest.ini")) or \
             os.path.exists(os.path.join(project_dir, "setup.py")):
            # Python project
            result = self._run_command("pytest", cwd=project_dir, timeout=120)
        else:
            return False, "", "No test framework detected"
        
        output = result["stdout"] + "\n" + result["stderr"]
        
        if result["success"]:
            return True, output, None
        else:
            return False, output, "Tests failed"
    
    def _run_lint(self, project_dir: str) -> tuple[bool, str, Optional[str]]:
        """Run linter in project directory."""
        # Detect linter
        if os.path.exists(os.path.join(project_dir, "package.json")):
            # Try ESLint
            result = self._run_command("npx eslint . --format=compact", cwd=project_dir, timeout=60)
        elif os.path.exists(os.path.join(project_dir, "pyproject.toml")):
            # Try Ruff
            result = self._run_command("ruff check .", cwd=project_dir, timeout=60)
        else:
            return True, "No linter configured", None
        
        output = result["stdout"] + "\n" + result["stderr"]
        
        if result["success"]:
            return True, output, None
        else:
            return False, output, "Linting errors found"
    
    def _auto_fix(self, project_dir: str, errors: str) -> tuple[bool, str, Optional[str]]:
        """
        Auto-fix errors using Claude.
        
        In production, this would:
        1. Parse error messages
        2. Use Claude to generate fixes
        3. Apply fixes to files
        4. Re-run tests
        """
        if not self._llm_api_key:
            return False, "", "LLM_API_KEY not configured for auto-fix"
        
        # TODO: Implement Claude API integration for auto-fixing
        # For now, try basic auto-fix commands
        
        # Try ESLint auto-fix
        result = self._run_command("npx eslint . --fix", cwd=project_dir, timeout=60)
        
        if result["success"]:
            return True, "Auto-fix applied", None
        else:
            return False, result["stderr"], "Auto-fix failed"
    
    def _iterate_until_pass(self, project_dir: str, max_iterations: int = 5) -> tuple[bool, Dict[str, Any], Optional[str]]:
        """
        Iterate: generate -> test -> lint -> fix until tests pass or max iterations reached.
        """
        iteration_log = []
        
        for i in range(max_iterations):
            logger.info(f"Iteration {i+1}/{max_iterations}")
            
            # Run tests
            test_success, test_output, test_error = self._run_tests(project_dir)
            iteration_log.append({
                "iteration": i + 1,
                "step": "test",
                "success": test_success,
                "output": test_output[:500]
            })
            
            if test_success:
                logger.info("Tests passed!")
                return True, {
                    "iterations": i + 1,
                    "status": "success",
                    "log": iteration_log
                }, None
            
            # Run lint
            lint_success, lint_output, lint_error = self._run_lint(project_dir)
            iteration_log.append({
                "iteration": i + 1,
                "step": "lint",
                "success": lint_success,
                "output": lint_output[:500]
            })
            
            # Try to auto-fix
            errors = test_output + "\n" + lint_output
            fix_success, fix_output, fix_error = self._auto_fix(project_dir, errors)
            iteration_log.append({
                "iteration": i + 1,
                "step": "fix",
                "success": fix_success,
                "output": fix_output[:500]
            })
            
            if not fix_success:
                logger.warning(f"Auto-fix failed on iteration {i+1}")
        
        return False, {
            "iterations": max_iterations,
            "status": "max_iterations_reached",
            "log": iteration_log
        }, f"Failed to pass tests after {max_iterations} iterations"
    
    def execute(self, **kwargs) -> SkillResult:
        start = time.time()
        
        # Validate parameters
        is_valid, error_msg = self.validate_parameters(**kwargs)
        if not is_valid:
            return SkillResult(
                success=False,
                result=None,
                error_message=error_msg,
                execution_time_ms=int((time.time() - start) * 1000)
            )
        
        action = kwargs.get("action")
        spec_path = kwargs.get("spec_path", "")
        project_dir = kwargs.get("project_dir", "jarvis_output/generated_project")
        max_iterations = kwargs.get("max_iterations", 5)
        
        try:
            if action == "generate":
                success, files, error = self._generate_code(spec_path, project_dir)
                result = {"files_created": files, "project_dir": os.path.abspath(project_dir)}
            
            elif action == "test":
                success, output, error = self._run_tests(project_dir)
                result = {"test_output": output}
            
            elif action == "lint":
                success, output, error = self._run_lint(project_dir)
                result = {"lint_output": output}
            
            elif action == "fix":
                success, output, error = self._auto_fix(project_dir, "")
                result = {"fix_output": output}
            
            elif action == "iterate":
                success, result, error = self._iterate_until_pass(project_dir, max_iterations)
            
            else:
                return SkillResult(
                    success=False,
                    result=None,
                    error_message=f"Unknown action: {action}",
                    execution_time_ms=int((time.time() - start) * 1000)
                )
            
            return SkillResult(
                success=success,
                result=result,
                error_message=error,
                execution_time_ms=int((time.time() - start) * 1000)
            )
            
        except Exception as e:
            logger.error(f"Code executor failed: {e}")
            return SkillResult(
                success=False,
                result=None,
                error_message=str(e),
                execution_time_ms=int((time.time() - start) * 1000)
            )
